# Generated by Django 3.2.7 on 2021-11-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20211009_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ManyToManyField(blank=True, to='post.Image'),
        ),
    ]
