# Generated by Django 3.2.7 on 2021-10-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
