# Generated by Django 3.2.7 on 2021-10-20 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_subject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.subject'),
        ),
    ]
