# Generated by Django 3.2.7 on 2021-10-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forumpost_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='view',
            field=models.IntegerField(default=1),
        ),
    ]
