# Generated by Django 3.2.7 on 2021-11-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20211110_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumreply',
            old_name='created_on',
            new_name='created',
        ),
    ]
