# Generated by Django 3.2.7 on 2021-11-11 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0007_rename_created_on_forumreply_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subscriber',
            field=models.ManyToManyField(blank=True, related_name='forum_subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
