# Generated by Django 3.2.7 on 2021-12-30 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_subject_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumreply',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forumpost_parent', to='forum.forumpost'),
        ),
    ]
