# Generated by Django 3.2.7 on 2021-11-24 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20211122_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='claps',
            field=models.ManyToManyField(blank=True, related_name='clap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='read_list',
            field=models.ManyToManyField(blank=True, related_name='read_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
