# Generated by Django 3.2.7 on 2021-10-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0003_auto_20211007_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followers',
        ),
    ]
