# Generated by Django 3.2.7 on 2021-10-27 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_product_price'),
        ('account', '0001_initial'),
        ('account_profile', '0004_remove_userprofile_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSavedPost',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.account')),
                ('products_saved', models.ManyToManyField(blank=True, to='marketplace.Product')),
            ],
        ),
    ]
