# Generated by Django 3.2.7 on 2022-01-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='the2048',
            options={'ordering': ['-score']},
        ),
        migrations.AddField(
            model_name='the2048',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='the2048',
            name='duration_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
